### ISSUE TITLE
Variant Support

### ISSUE THREAD

**Issue by ghost** [narendrans/dremio-snowflake#11]
**What would you like to be added**:

Currently, I cannot request json-variants (like the waether-snowflake-testdataset). I get the error-message _Failure while attempting to read from database_.

 Is there a way I do not see right now?

Thanks! :)

**Comment by narendrans** [comment]
`VARIANT` types will be shown as a `VARCHAR`. You can then use `convert_from(<field>, 'JSON')` in Dremio to treat it like a JSON object. After which you should be able to extract an object or unnest an array.

Native JSON mapping requires implementation in the core SDK. I will update the code when we have it. For now, the above should work. Tested it on the following datasets:

`"SNOWFLAKE_SAMPLE_DATA".WEATHER."DAILY_14_TOTAL"`
`"SNOWFLAKE_SAMPLE_DATA".WEATHER."WEATHER_14_TOTAL"`

**Comment by ghost** [comment]
Perfect, everything works as expected!

Thank you!
