### ISSUE TITLE
SQL Error: VALIDATION ERROR: Expression 'EC.PARENT_EKEY' is not being grouped

### ISSUE THREAD

**Issue by ParensAllTheWayDown** [narendrans/dremio-snowflake#12]
**What happened**:

Perform select statement through JDBC Connection (or GUI) and receive VALIDATION ERROR.

```
SELECT *
FROM "sf-dremio"."PROD_TEMP"."TEMP"."EQUIP" E
INNER JOIN "sf-dremio"."PROD_TEMP"."TEMP"."EQUIPCLUSTER" EC ON E.EKEY = EC.PARENT_EKEY
INNER JOIN "sf-dremio"."PROD_TEMP"."TEMP"."EQUIP" CE ON CE.EKEY = EC.CHILD_EKEY
order by E.VALUE
limit 2
```
Results in following JDBC error returned:
```
SQL Error: PARSE ERROR: Failure parsing the query.

SQL Query SELECT *
FROM "sf-dremio"."PROD_TEMP"."TEMP"."EQUIP" E
INNER JOIN "sf-dremio"."PROD_TEMP"."TEMP"."EQUIPCLUSTER" EC ON E.EKEY = EC.PARENT_EKEY
INNER JOIN "sf-dremio"."PROD_TEMP"."TEMP"."EQUIP" CE ON CE.EKEY = EC.CHILD_EKEY
order by E.VALUE
limit 2

startLine 5
startColumn 11
endLine 5
endColumn 11
SQL Query SELECT *
FROM "sf-dremio"."PROD_TEMP"."TEMP"."EQUIP" E
INNER JOIN "sf-dremio"."PROD_TEMP"."TEMP"."EQUIPCLUSTER" EC ON E.EKEY = EC.PARENT_EKEY
INNER JOIN "sf-dremio"."PROD_TEMP"."TEMP"."EQUIP" CE ON CE.EKEY = EC.CHILD_EKEY
```

**What you expected to happen**:

Would expect it to not result in an invalid QUERY.

**How to reproduce it (as minimally and precisely as possible)**:

In snowflake, 
```
create or replace table PROD_TEMP.TEMP.Equip (ekey integer, ename varchar(20), value float)
create or replace table PROD_TEMP.TEMP.EquipCluster (ecKey integer AUTOINCREMENT, parent_ekey integer, child_ekey integer, rtype varchar(10), active boolean)
```

I use dbeaver to create test data using following method.
create 1000 Equip with sequential ekey ename is random 'Ipsum lorum' value is random float.
create series of parent_ekey starting at 1 stepping by 3
create series of child_ekey starting at 2 stepping by 3

**Anything else we need to know?**:

**Details**:
- Dremio version (Help > About from the UI):

**FULL DISCLOSURE** this is OSS Dremio with some extras.
```
Build
3.2.4-201906051751050278-1bcce62
Edition
Community Edition
Build Time
06/06/2019 22:42:55
Change Hash
1bcce62ffcffe357f061f68993038a98ba58347d
Change Time
06/05/2019 13:44:25
```

- Profile zip:
- server.log:
```
2019-08-13 19:53:05,298 [out-of-band-observer] INFO  query.logger - {"queryId":"22aceade-5af1-4f3a-e409-c17b989c5600","queryText":"SELECT *\nFROM \"sf-dremio\".\"PROD_TEMP\".\"TEMP\".\"EQUIP\" E\nINNER JOIN \"sf-dremio\".\"PROD_TEMP\".\"TEMP\".\"EQUIPCLUSTER\" EC ON E.EKEY = EC.PARENT_EKEY\nINNER JOIN \"sf-dremio\".\"PROD_TEMP\".\"TEMP\".\"EQUIP\" CE ON CE.EKEY = EC.CHILD_EKEY\norder by E.VALUE\nlimit 2\n","start":1565725985294,"finish":1565725985296,"outcome":"FAILED","username":"admin"}
```

**Comment by narendrans** [comment]
Surround VALUE with double quotes as VALUE is a [reserved keyword](https://docs.dremio.com/sql-reference/reserved-keywords.html). For example:

`SELECT *
FROM "EQUIP" E
INNER JOIN "EQUIPCLUSTER" EC ON E.EKEY = EC.PARENT_EKEY
INNER JOIN "EQUIP" CE ON CE.EKEY = EC.CHILD_EKEY
order by E."VALUE"
limit 2`

**Comment by ParensAllTheWayDown** [comment]
Bah.  You are right.  I've got a problem, but can't seem to replicate it cleanly with fake data... will try again when other fires have been extinguished.
