### ISSUE TITLE
Credential rejection action

### ISSUE THREAD

**Issue by ParensAllTheWayDown** [narendrans/dremio-snowflake#17]
**What would you like to be added**:
It would be nice to be able to take some action if the jdbc connection failed.  Either on initial setup or at the time of query.
**Why is this needed**:
For example, if the jdbc connection fails because the username/password has changed on the source database (policy to roll passwords periodically), it would be nice to be able to execute code that would enable us to re-fresh the credential from an external source of username/passwords (a password vault).

**Comment by narendrans** [comment]
The functionality for this requires changes in the core product. The alternative way is to check the source via a polling mechanism and change the source credentials via API.
