### ISSUE TITLE
integers and other whole numbers should be presented as integer

### ISSUE THREAD

**Issue by ParensAllTheWayDown** [narendrans/dremio-snowflake#18]
**What would you like to be added**:
Snowflake Numbers where scale == 0 should be interpreted as integer type. (or long or other non-floating representation).

**Why is this needed**:
snowflake default integer implementation datatype is 'number(38,0)' [reference](https://docs.snowflake.net/manuals/sql-reference/data-types-numeric.html#int-integer-bigint-smallint-tinyint-byteint)
In in dremio-snowflake plugin, all numerics are presented as floating representation rather than integer in cases where the scale == 0.
for example, something inserted into snowflake as the integer 5 is extracted and presented in dremio as #.# or 5.0

**Comment by naren-dremio** [comment]
Snowflake DDL for repro:

```
create table test (id int);
insert into test values (12);
```

**Comment by narendrans** [comment]
Snowflake DDL for repro:

```
create table test (id int);
insert into test values (12);
```

**Comment by narendrans** [comment]
_To be fixed in the next major release end of next week._

**Comment by narendrans** [comment]
_The changes needed for this is addressed in the ARP framework itself to make it more robust. Closing it for now and will update when its done (Expected timeline is 1 week)_
