### ISSUE TITLE
Authentication token has expired.  The user must authenticate again.

### ISSUE THREAD

**Issue by patricker** [narendrans/dremio-snowflake#19]
**What happened**: 
After using the plugin successfully for a week or so all queries started failing against Snowflake.  When we looked at the Job Profile we were able to see the following error from the Snowflake JDBC driver:  (net.snowflake.client.jdbc.SnowflakeReauthenticationRequest) Authentication token has expired.  The user must authenticate again.

**What you expected to happen**:
Reauthentication would be handled automatically and queries would continue to work.

**How to reproduce it (as minimally and precisely as possible)**:
Don't restart your executors very often?  Not sure.

**Anything else we need to know?**:
We are running all of our executors provisioned on YARN.  Restarting Dremio did not resolve this error, but restarting the provisioned executors did. This makes sense, since the Snowflake authentication was actually being performed on the executors.  Full stack trace of the error follows:

      DATA_READ ERROR: The JDBC storage plugin failed while trying setup the SQL query. 

sql SELECT *
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS" LIMIT 2000 OFFSET 0
plugin sf2
SqlOperatorImpl JDBC_SUB_SCAN
Location 0:0:6
SqlOperatorImpl JDBC_SUB_SCAN
Location 0:0:6
Fragment 0:0

[Error Id: 41bd1430-0393-4872-b04f-b8b2411b463c on {servername}:-1]

  (net.snowflake.client.jdbc.SnowflakeReauthenticationRequest) Authentication token has expired.  The user must authenticate again.
    net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub():135
    net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionIncludingReauth():58
    net.snowflake.client.core.SessionUtil.tokenRequest():909
    net.snowflake.client.core.SessionUtil.renewSession():775
    net.snowflake.client.core.SFSession.renewSession():690
    net.snowflake.client.core.SFStatement.executeHelper():512
    net.snowflake.client.core.SFStatement.executeQueryInternal():247
    net.snowflake.client.core.SFStatement.executeQuery():186
    net.snowflake.client.core.SFStatement.execute():790
    net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal():245
    net.snowflake.client.jdbc.SnowflakeStatementV1.executeQuery():166
    org.apache.commons.dbcp2.DelegatingStatement.executeQuery():206
    org.apache.commons.dbcp2.DelegatingStatement.executeQuery():206
    com.dremio.exec.store.jdbc.JdbcRecordReader.setup():197
    com.dremio.exec.store.CoercionReader.setup():109
    com.dremio.sabot.op.scan.ScanOperator$1.run():220
    com.dremio.sabot.op.scan.ScanOperator$1.run():216
    java.security.AccessController.doPrivileged():-2
    javax.security.auth.Subject.doAs():422
    org.apache.hadoop.security.UserGroupInformation.doAs():1836
    com.dremio.sabot.op.scan.ScanOperator.setupReaderAsCorrectUser():216
    com.dremio.sabot.op.scan.ScanOperator.setupReader():189
    com.dremio.sabot.op.scan.ScanOperator.setup():175
    com.dremio.sabot.driver.SmartOp$SmartProducer.setup():558
    com.dremio.sabot.driver.Pipe$SetupVisitor.visitProducer():79
    com.dremio.sabot.driver.Pipe$SetupVisitor.visitProducer():63
    com.dremio.sabot.driver.SmartOp$SmartProducer.accept():528
    com.dremio.sabot.driver.StraightPipe.setup():102
    com.dremio.sabot.driver.StraightPipe.setup():102
    com.dremio.sabot.driver.StraightPipe.setup():102
    com.dremio.sabot.driver.StraightPipe.setup():102
    com.dremio.sabot.driver.StraightPipe.setup():102
    com.dremio.sabot.driver.StraightPipe.setup():102
    com.dremio.sabot.driver.Pipeline.setup():68
    com.dremio.sabot.exec.fragment.FragmentExecutor.setupExecution():360
    com.dremio.sabot.exec.fragment.FragmentExecutor.run():244
    com.dremio.sabot.exec.fragment.FragmentExecutor.access$1200():92
    com.dremio.sabot.exec.fragment.FragmentExecutor$AsyncTaskImpl.run():632
    com.dremio.sabot.task.AsyncTaskWrapper.run():104
    com.dremio.sabot.task.slicing.SlicingThread.mainExecutionLoop():226
    com.dremio.sabot.task.slicing.SlicingThread.run():156
 

**Details**:
- Dremio version (Help > About from the UI): 3.2.4
- Profile zip:
- server.log:

**Comment by narendrans** [comment]
@patricker Can you test by adding the JDBC property `CLIENT_SESSION_KEEP_ALIVE` to `true`? 
Make sure to use v3.0.18+ driver. The latest is `3.9.2`: https://mvnrepository.com/artifact/net.snowflake/snowflake-jdbc/3.9.2

`jdbc:snowflake://<account_name>.snowflakecomputing.com/?CLIENT_SESSION_KEEP_ALIVE=true`

Check out this link for more information:
https://snowflakecommunity.force.com/s/question/0D50Z00006xVtEmSAK/using-clientsessionkeepalive-in-jdbc-connection-string

**Comment by patricker** [comment]
Thanks @narendrans. We are currently using snowflake-jdbc-3.8.7.  I will try adding that parameter to the connection string.

**Comment by mchristopher** [comment]
@narendrans I just submitted a PR that adds this property to the connection. Based on how long-lived Dremio connections are, I made the assumption that forcing the property on was the expected behavior for users.
