### ISSUE TITLE
Not able to connect to Snowflake through Dremio

### ISSUE THREAD

**Issue by harikrushna2815** [narendrans/dremio-snowflake#21]
**What happened**:
Recently we have started using Dremio(Data as Service) and tried connecting to Snowflake.

**What you expected to happen**:

While connecting to Snowflake from Dremio and it is throwing following error message
**************************************
**ERROR Unavailable: Unable to find handler for source of type [SNOWFLAKE]**

**SOURCE_BAD_STATE ERROR: The source [<source name>] is currently unavailable. Info: [Unavailable: Unable to find handler for source of type [SNOWFLAKE].]**

**ERROR Unavailable: Unable to find handler for source of type [SNOWFLAKE].**

**Fragment 1:0**

**[Error Id: 1fefea06-ec0a-42e9-bb76-07433574466d on <Dremio Executor>:-1]**

**ERROR Unavailable: Unable to find handler for source of type [SNOWFLAKE].**

**Fragment 1:0**

**************************************

**How to reproduce it (as minimally and precisely as possible)**:
Use Dremio(Data as Service) and try connecting to snowflake using available connectors

**Anything else we need to know?**:

**Details**:
- Dremio version (Help > About from the UI): Dremio 3.0
- Profile zip:
- server.log:

**Comment by narendrans** [comment]
Check if the driver and the plugin are properly installed (must be dropped in the jars directory)
