### ISSUE TITLE
Limits not pushing down?

### ISSUE THREAD

**Issue by patricker** [narendrans/dremio-snowflake#25]
**What happened**:
When previewing or limiting data, the limit appears to happen locally.

**What you expected to happen**:
Limit pushdown

**How to reproduce it (as minimally and precisely as possible)**:
Latest version of SF plugin with Dremio 4.1.8.

**Anything else we need to know?**:

**Details**:
- Dremio version (Help > About from the UI): 4.1.8

**Job Plan**
00-00    Screen : rowType = RecordType(VARCHAR(65536) Fragment, BIGINT Records, VARCHAR(65536) Path, VARBINARY(65536) Metadata, INTEGER Partition, BIGINT FileSize): rowcount = 10000.0, cumulative cost = {3071000.0 rows, 1.351411374E8 cpu, 1.35E8 io, 3.8076E8 network, 0.0 memory}, id = 12903
00-01      Project(Fragment=[$0], Records=[$1], Path=[$2], Metadata=[$3], Partition=[$4], FileSize=[$5]) : rowType = RecordType(VARCHAR(65536) Fragment, BIGINT Records, VARCHAR(65536) Path, VARBINARY(65536) Metadata, INTEGER Partition, BIGINT FileSize): rowcount = 10000.0, cumulative cost = {3070000.0 rows, 1.351401374E8 cpu, 1.35E8 io, 3.8076E8 network, 0.0 memory}, id = 12902
00-02        WriterCommitter(final=[/dremio/results/2158c827-9073-36f6-ec60-c53216909d00]) : rowType = RecordType(VARCHAR(65536) Fragment, BIGINT Records, VARCHAR(65536) Path, VARBINARY(65536) Metadata, INTEGER Partition, BIGINT FileSize): rowcount = 10000.0, cumulative cost = {3060000.0 rows, 1.351401368E8 cpu, 1.35E8 io, 3.8076E8 network, 0.0 memory}, id = 12901
00-03          UnionExchange : rowType = RecordType(VARCHAR(65536) Fragment, BIGINT Records, VARCHAR(65536) Path, VARBINARY(65536) Metadata, INTEGER Partition, BIGINT FileSize): rowcount = 10000.0, cumulative cost = {3050000.0 rows, 1.351301368E8 cpu, 1.35E8 io, 3.8076E8 network, 0.0 memory}, id = 12900
01-01            Writer : rowType = RecordType(VARCHAR(65536) Fragment, BIGINT Records, VARCHAR(65536) Path, VARBINARY(65536) Metadata, INTEGER Partition, BIGINT FileSize): rowcount = 10000.0, cumulative cost = {3040000.0 rows, 1.350501368E8 cpu, 1.35E8 io, 1.35E8 network, 0.0 memory}, id = 12899
01-02              Project(O_ORDERKEY=[$0], O_CUSTKEY=[$1], O_ORDERSTATUS=[$2], O_TOTALPRICE=[$3], O_ORDERDATE=[$4], O_ORDERPRIORITY=[$5], O_CLERK=[$6], O_SHIPPRIORITY=[$7], O_COMMENT=[$8]) : rowType = RecordType(DECIMAL(38, 0) O_ORDERKEY, DECIMAL(38, 0) O_CUSTKEY, VARCHAR(65536) O_ORDERSTATUS, DECIMAL(12, 2) O_TOTALPRICE, DATE O_ORDERDATE, VARCHAR(65536) O_ORDERPRIORITY, VARCHAR(65536) O_CLERK, DECIMAL(38, 0) O_SHIPPRIORITY, VARCHAR(65536) O_COMMENT): rowcount = 10000.0, cumulative cost = {3030000.0 rows, 1.350401368E8 cpu, 1.35E8 io, 1.35E8 network, 0.0 memory}, id = 12898
01-03                Project(O_ORDERKEY=[$0], O_CUSTKEY=[$1], O_ORDERSTATUS=[$2], O_TOTALPRICE=[$3], O_ORDERDATE=[$4], O_ORDERPRIORITY=[$5], O_CLERK=[$6], O_SHIPPRIORITY=[$7], O_COMMENT=[$8]) : rowType = RecordType(DECIMAL(38, 0) O_ORDERKEY, DECIMAL(38, 0) O_CUSTKEY, VARCHAR(65536) O_ORDERSTATUS, DECIMAL(12, 2) O_TOTALPRICE, DATE O_ORDERDATE, VARCHAR(65536) O_ORDERPRIORITY, VARCHAR(65536) O_CLERK, DECIMAL(38, 0) O_SHIPPRIORITY, VARCHAR(65536) O_COMMENT): rowcount = 10000.0, cumulative cost = {3020000.0 rows, 1.350401359E8 cpu, 1.35E8 io, 1.35E8 network, 0.0 memory}, id = 12897
01-04                  Limit(offset=[0], fetch=[10000]) : rowType = RecordType(DECIMAL(38, 0) O_ORDERKEY, DECIMAL(38, 0) O_CUSTKEY, VARCHAR(65536) O_ORDERSTATUS, DECIMAL(12, 2) O_TOTALPRICE, DATE O_ORDERDATE, VARCHAR(65536) O_ORDERPRIORITY, VARCHAR(65536) O_CLERK, DECIMAL(38, 0) O_SHIPPRIORITY, VARCHAR(65536) O_COMMENT): rowcount = 10000.0, cumulative cost = {3010000.0 rows, 1.35040135E8 cpu, 1.35E8 io, 1.35E8 network, 0.0 memory}, id = 12896
01-05                    Project(O_ORDERKEY=[$0], O_CUSTKEY=[$1], O_ORDERSTATUS=[$2], O_TOTALPRICE=[$3], O_ORDERDATE=[$4], O_ORDERPRIORITY=[$5], O_CLERK=[$6], O_SHIPPRIORITY=[$7], O_COMMENT=[$8]) : rowType = RecordType(DECIMAL(38, 0) O_ORDERKEY, DECIMAL(38, 0) O_CUSTKEY, VARCHAR(65536) O_ORDERSTATUS, DECIMAL(12, 2) O_TOTALPRICE, DATE O_ORDERDATE, VARCHAR(65536) O_ORDERPRIORITY, VARCHAR(65536) O_CLERK, DECIMAL(38, 0) O_SHIPPRIORITY, VARCHAR(65536) O_COMMENT): rowcount = 1500000.0, cumulative cost = {3000000.0 rows, 1.35000135E8 cpu, 1.35E8 io, 1.35E8 network, 0.0 memory}, id = 12895
01-06                      Jdbc(sql=[SELECT "ORDERS"."O_ORDERKEY", "ORDERS"."O_CUSTKEY", "ORDERS"."O_ORDERSTATUS", "ORDERS"."O_TOTALPRICE", "ORDERS"."O_ORDERDATE", "ORDERS"."O_ORDERPRIORITY", "ORDERS"."O_CLERK", "ORDERS"."O_SHIPPRIORITY", "ORDERS"."O_COMMENT"
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS"]) : rowType = RecordType(DECIMAL(38, 0) O_ORDERKEY, DECIMAL(38, 0) O_CUSTKEY, VARCHAR(65536) O_ORDERSTATUS, DECIMAL(12, 2) O_TOTALPRICE, DATE O_ORDERDATE, VARCHAR(65536) O_ORDERPRIORITY, VARCHAR(65536) O_CLERK, DECIMAL(38, 0) O_SHIPPRIORITY, VARCHAR(65536) O_COMMENT): rowcount = 1500000.0, cumulative cost = {1500000.0 rows, 1.35E8 cpu, 1.35E8 io, 1.35E8 network, 0.0 memory}, id = 12805

**Comment by narendrans** [comment]
@patricker Thanks for reporting this. This is a known issue in the 4.x version of Dremio. As a temporary workaround, set this property `planner.enable_relational_planning` to `false` and try. The query will have limit pushed to snowflake. I don't recommend disabling this flag though. Will keep you posted if a release containing a fix to this is out.

**Comment by patricker** [comment]
Yikes.  You've got me worried about upgrading now.  We are also running into https://github.com/snowflakedb/snowflake-jdbc/issues/212, only after upgrading for the same version of the Snowflake JDBC driver (though we are working with Snowflake on that specific issue).

**Comment by narendrans** [comment]
Tested with 4.9.1.

On Preview it uses the JDBC fetch limit:

`sql=[SELECT *
FROM (SELECT "CUSTOMER"."C_CUSTKEY", "CUSTOMER"."C_NAME", "CUSTOMER"."C_ADDRESS", "CUSTOMER"."C_NATIONKEY", "CUSTOMER"."C_PHONE", "CUSTOMER"."C_ACCTBAL", "CUSTOMER"."C_MKTSEGMENT", "CUSTOMER"."C_COMMENT"
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" LIMIT 2000 OFFSET 0) AS "CUSTOMER" LIMIT 100]`

On run it pushes the limit:

`sql=[SELECT "CUSTOMER"."C_CUSTKEY", "CUSTOMER"."C_NAME", "CUSTOMER"."C_ADDRESS", "CUSTOMER"."C_NATIONKEY", "CUSTOMER"."C_PHONE", "CUSTOMER"."C_ACCTBAL", "CUSTOMER"."C_MKTSEGMENT", "CUSTOMER"."C_COMMENT"
FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" LIMIT 100]`
