### ISSUE TITLE
Add SQL functions to snowflake-arp.yaml 

### ISSUE THREAD

**Issue by jabaier117** [narendrans/dremio-snowflake#26]
**What would you like to be added**:
There are a handful of SQL functions/operators that I would like to see added to the snowflake-arp.yaml file.  I have added several that are commonly used by my team and will be submitting a PR shortly.  I have tested each addition and examined the query profile details to ensure it now gets pushed down.  

**Why is this needed**:
If the names/signatures don't exist in the snowflake-arp.yaml file, then predicates that use the function don't get pushed down.  My team utilizes snowflake extensively; predicate pushdown is critical for queries to be more performant.

**Comment by narendrans** [comment]
@jabaier117 Thanks for the PR. I will review and merge it.
