### ISSUE TITLE
Snowflake connector for Dremio v19.1

### ISSUE THREAD

**Issue by Janani-Reddy** [narendrans/dremio-snowflake#43]
Hi Naren/Team,

I see that we have snowflake plugin jars for different versions. And latest one is for Dremio v17.

**What would you like to be added**: I would like to setup connectivity to Snowflake from Dremio v19.1 with basic authentication(username and password).

**Why is this needed**: I need this so that we can query on Snowflake data from Dremio.

Thanks,
Janani

**Comment by narendrans** [comment]
Here: https://github.com/narendrans/dremio-snowflake/releases/tag/19.1.0
