### ISSUE TITLE
Dremio - Snowflake Community Connector - Future

### ISSUE THREAD

**Issue by venuamudala** [narendrans/dremio-snowflake#47]
@narendrans - I see that there was a release in November supporting Dremio v23. 

But, I see that there is going to be an official Snowflake Plugin from Dremio starting v23 & looks like they are not going to support the Community Plug-in anymore. 

I just wanted to check with you to see if there would be anymore updates for the Community Plug-in. 

Appreciate your response. Thanks !

![image](https://user-images.githubusercontent.com/9663573/208741949-997ad43a-f3b1-4eb9-905c-42423792aa1b.jpeg)

**Comment by naren-dremio** [comment]
Correct. Dremio now ships Snowflake connector out of the box so this repository won't be maintained anymore.
