### ISSUE TITLE
Use Warehouse

### ISSUE THREAD

**Issue by ghost** [narendrans/dremio-snowflake#8]
**What would you like to be added**:

A description where the Snowflake-Warehouse (and the user-role) can be specified. 

Thanks

**Comment by narendrans** [comment]
I have addressed this in 1.2: https://github.com/narendrans/dremio-snowflake/releases/tag/1.2. You can now specify those in the JDBC URL itself. For example:

`jdbc:snowflake://<account name>.snowflakecomputing.com/?warehouse=<warehouse>&role=<role>`

For more information on JDBC connection parameters, refer to: https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html
