### ISSUE TITLE
Error setting up remote fragment execution

### ISSUE THREAD

**Issue by ghost** [narendrans/dremio-snowflake#9]
I do not know whether this is a bug: the error-msg "Error setting up remote fragment execution" is shown in the context of a simple SELECT *-statement...

What can the reason be for this?

**Comment by ghost** [comment]
The above mentioned issue is probably related to my java-installation: I will check asap! 

BTW: If you have a dremio-docker-imagefile with your jar included...I would take it :) 

Thanks for your good support!

**Comment by narendrans** [comment]
I haven't seen such errors. Let me know how it goes..

For docker, try the following :)

Create a Dockerfile with the following content in a folder:

_FROM dremio/dremio-oss
USER root
RUN  cd /opt/dremio/jars && wget https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.8.8/snowflake-jdbc-3.8.8.jar && wget https://github.com/narendrans/dremio-snowflake/releases/download/1.2/dremio-snowflake-plugin-3.3.1-201907291852280797-df23756.jar && chown dremio snowflake-jdbc-3.8.8.jar dremio-snowflake-plugin-3.3.1-201907291852280797-df23756.jar_

Then build:

`docker build . -t dremio-snowflake`

And finally run:

`docker run -p 9047:9047 -p 31010:31010 dremio-snowflake`

**Comment by ParensAllTheWayDown** [comment]
I believe I have run into this issue in the past.  _At least in my case, it was related to a mis-configured linux host -- 'localhost' was not set correctly in /etc/hosts._  Traced this back to DACDaemonModule.java:261 FabricServiceImpl.getAddress.

But again, that was several months ago and I've slept since then.

**Comment by ghost** [comment]
The error disappeared in a docker-env :)
